=== brdegenars/PRO390-Nomad/Code/Tuts, Examples, and Wrestles/bDegenaars_jaxb/Contacts.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="myContacts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contact" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

<xs:element name="contact">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="email" type="xs:string"/>
      <xs:element ref="address" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="address">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="address1" type="xs:string"/>
      <xs:element name="address2" type="xs:string"/>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="state" type="xs:string"/>
      <xs:element name="zip" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== brdegenars/PRO390-Nomad/Code/Tuts, Examples, and Wrestles/bDegenaars_jaxb/MyContacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<myContacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Contacts.xsd">
  <contact>
    <name>Jake Walkenhorst</name>
    <email>jwalkenhorst@neumont.edu</email>
    <address>
      <address1>Neumont University</address1>
      <address2>10701 Riverfront Pkwy. Suite 300</address2>
      <city>South Jordan</city>
      <state>UT</state>
      <zip>84095</zip>
    </address>
  </contact>
  <contact>
  	<name>Joe Student</name>
  	<email>jstudent@student.neumont.edu</email>
  	<address>
  		<address1>1234 Easy St.</address1>
  		<address2></address2>
  		<city>Nowhere</city>
  		<state>USA</state>
  		<zip>00000</zip>
  	</address>
  </contact>
  <contact>
  	<name>Timmy Smithy</name>
  	<email>timmy@gmail.com</email>
  	<address>
  		<address1>1313 Mockingbird Ln.</address1>
  		<address2></address2>
  		<city>Muenster</city>
  		<state>OH</state>
  		<zip>22334</zip>
  	</address>  	
  </contact>
</myContacts>
